backend/config/routes.rb
Rails.application.routes.draw do

  resources :patients do
    resources :medications, except: [:show]
    resources :schedules, only: [:index] do
      post :update_confirmation, on: :collection
    end
  end
  # resources :medications, except: [:show]
  # resources :schedules, only: [:index]

  # post '/schedules/update_confirmation', to: 'schedules#update_confirmation'

  get 'rooms/show'

  root 'home#index'
  get 'home/index'
  get 'home/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # ログアウト時にエラーが出るので、以下を追加
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

backend/app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :medication
end

backend/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  # ログインしていないユーザーをログインページに促す
  before_action :authenticate_user!
  # URLからパラメーターを取得し、@patientに代入する
  before_action :set_patient

  # 今日の服用スケジュールを取得し、一覧表示する
  def index
    date = params[:date]&.to_date || Date.current
    schedules_on_date = Schedule.joins(:medication).where(medications: { secret_patient_id: @patient.secret_id}, date: date)
    schedules_sorted_by_time = schedules_on_date.sort_by do |schedule|
      schedule.medication.send("time#{schedule.time_slot}").seconds_since_midnight
    end
    @schedules = schedules_sorted_by_time
    @date = date
  end

  # 服用スケジュールの確認状況を更新する
  def update_confirmation
    schedule_id = params[:schedule_id]
    checked = params[:checked]
    schedule = Schedule.find(schedule_id)

    if checked == "true" # JavaScriptから送信された値は文字列として扱われることがあるため
      schedule.update(confirmation: true)
    else
      schedule.update(confirmation: false)
    end

    respond_to do |format|
      format.json { render json: { success: true } } # JSON形式で成功レスポンスを返す
    end
  end

  private

  def set_patient
    @patient = Patient.find(params[:patient_id])
  end
end

backend/app/helpers/schedules_helper.rb
module SchedulesHelper
end

backend/app/views/schedules/index.html.erb
<div class="container mt-5 mb-5">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <h2 class="mb-3"><%= @date.strftime("%Y年%-m月") %></h2>

      <div class="schedule-last-next">
        <% last_start_date = @date-7 %>
        <% next_start_date = @date+7 %>
        <%= link_to "◀", patient_schedules_path(@patient, date: last_start_date), class: "btn last-week-button", title: "前の週" %>
        <%= link_to "▶", patient_schedules_path(@patient, date: next_start_date), class: "btn next-week-button", title: "次の週"  %>
        <%= link_to "今日", patient_schedules_path(@patient, date: Date.current), class: "btn today-button"%>
      </div>

      <div class="schedule-week">
        <% start_date = @date.beginning_of_week(:monday) %>
        <% 7.times do |i| %>
          <%= link_to "#{start_date.strftime("%-d")} (#{japanese_weekday(start_date)})", patient_schedules_path(@patient, date: start_date), class: "btn date-button #{'selected-date' if @date == start_date}" %>
          <% start_date += 1.day %>
        <% end %>
      </div>

      <% if @schedules.present? %>  <!-- スケジュールがある場合 -->
        <div class="schedule-cards">
          <% @schedules.each do |schedule| %>
            <div class="card <%= 'card-confirmed' if schedule.confirmation %> ">
              <div class="card-body d-flex align-items-center">
                <button class="confirm-button <%= 'confirmed' if schedule.confirmation %>" data-schedule-id="<%= schedule.id %>" data-url="<%= update_confirmation_patient_schedules_path(@patient) %>" >
                  ✓
                </button>
                <div class="schedule-details">
                  <div class="time"><%= schedule.medication.send("time#{schedule.time_slot}").strftime('%H:%M') %></div>
                  <div class="name"><%= schedule.medication.name %></div>
                  <div class="dosage"><%= schedule.medication.dosage %></div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>      <!-- スケジュールがない場合 -->
        <div class="no-schedule">
          <%= image_tag "no-schedule.svg", class: "no-schedule-img" %>
          <p>本日の服用スケジュールがありません</p>
        </div>
      <% end %>
    </div>
  </div>
</div>