backend/config/routes.rb
Rails.application.routes.draw do

  resources :patients do
    resources :medications, except: [:show]
    resources :schedules, only: [:index] do
      post :update_confirmation, on: :collection
    end
  end
  # resources :medications, except: [:show]
  # resources :schedules, only: [:index]

  # post '/schedules/update_confirmation', to: 'schedules#update_confirmation'

  get 'rooms/show'

  root 'home#index'
  get 'home/index'
  get 'home/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # ログアウト時にエラーが出るので、以下を追加
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

backend/app/models/medication.rb
class Medication < ApplicationRecord
  has_many :schedules, dependent: :destroy

  belongs_to :patient, foreign_key: :secret_patient_id, primary_key: :secret_id

  after_create :create_schedules

  after_update :update_schedules

  validates :name, presence: true
  validates :dosage, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date

  private

  # 薬が新規登録されたあとに、服用スケジュールを作成する
  def create_schedules
    (start_date..end_date).each do |date|
      [time1, time2, time3, time4, time5].each_with_index do |time, index|
        self.schedules.create(date: date, time_slot: index + 1, confirmation: false) if time.present?
      end
    end
  end

  # 薬の情報が更新されたあとに、服用スケジュールを更新する
  def update_schedules
    # 既存の服用スケジュールを全て削除する
    self.schedules.destroy_all
    # 服用スケジュールを再作成する
    create_schedules
  end

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

end

backend/app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
  #　ログインしていないユーザーをログインページに促す
  before_action :authenticate_user!
  # データを新規作成するためのフォームを表示する
  def new
    @medication = current_patient.medications.build
  end

  # データを新規作成し、DBに保存する
  def create
    @medication = current_patient.medications.build(medication_params)

    respond_to do |format|
      if @medication.save
        format.html {redirect_to patient_medications_path, notice: 'お薬を登録しました'}
      else
        format.html {render :new, status: :unprocessable_entity}
      end
    end
  end

  # 全てのデータを取得し、一覧表示する
  def index
    @medications = current_patient.medications
  end

  # 特定のデータを取得し、編集するためのフォームを表示する
  def edit
    @medication = current_patient.medications.find(params[:id])
  end

  # データを更新する
  def update
    @medication = current_patient.medications.find(params[:id])

    respond_to do |format|
      if @medication.update(medication_params)
        format.html {redirect_to patient_medications_path, notice: 'お薬情報を更新しました'}
      else
        format.html {render :edit, status: :unprocessable_entity}
      end
    end
  end

  # データを削除する
  def destroy
    @medication = current_patient.medications.find(params[:id])
    @medication.destroy

    respond_to do |format|
      format.html {redirect_to patient_medications_path, notice: 'お薬を削除しました', status: :see_other}
    end
  end

  private
  # ストロングパラメーター
  def medication_params
    params.require(:medication).permit(:name, :dosage, :start_date, :end_date, :memo, :time1, :time2, :time3, :time4, :time5)
  end
end

backend/app/helpers/medications_helper.rb
module MedicationsHelper
end

backend/app/views/medications/_errors.html.erb
<% if @medication.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(@medication.errors.count, "個") %> のエラーがあるため登録できません</h2>
    <ul>
      <% @medication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

backend/app/views/medications/_form.html.erb
<%= form_with model: [current_patient, @medication], local: true do |form| %>
  <div class="mb-3">
    <%= form.label :name, "名前", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="row mb-3">
    <div class="col-4">
      <%= form.label :dosage, "服用量", class: "form-label" %>
      <%= form.text_field :dosage, class: "form-control" %>
    </div>

    <div class="col-4">
      <%= form.label :start_date, "開始日", class: "form-label" %>
      <%= form.date_field :start_date, class: "form-control" %>
    </div>

    <div class="col-4">
      <%= form.label :end_date, "終了日", class: "form-label" %>
      <%= form.date_field :end_date, class: "form-control" %>
    </div>
  </div>


  <div class="row mb-3">
    <div class="col-4 time-input visible">
      <%= form.label :time1, "時間" %>
      <%= form.time_field :time1, class: "form-control time-field" %>
    </div>

    <div class="col-4 time-input label-placeholder" >
      <%= form.time_field :time2, class: "form-control time-field" %>
    </div>

    <div class="col-4 time-input label-placeholder">
      <%= form.time_field :time3, class: "form-control time-field" %>
    </div>
  </div>

  <div class="row">
    <div class="col-4 time-input" >
      <%= form.time_field :time4, class: "form-control time-field" %>
    </div>

    <div class="col-4 time-input" >
      <%= form.time_field :time5, class: "form-control time-field" %>
    </div>
  </div>

  <div class="mb-3 mt-3">
    <%= form.label :memo, "メモ", class: "form-label" %>
    <%= form.text_area :memo, class: "form-control large-text-area" %>
  </div>

  <div class="mb-3">
    <%= form.submit "登        録", class: "btn new-button w-50" %>
  </div>

<% end %>

backend/app/views/medications/create.html.erb
<h1>Medications#create</h1>
<p>Find me in app/views/medications/create.html.erb</p>

backend/app/views/medications/edit.html.erb
<div class="container mb-5">
  <%= link_to "戻る", patient_medications_path(current_patient), class: "btn back-button" %>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h3 class="text-center mb-3">お薬情報編集</h3>
      <hr>

      <%= render 'errors' %>

      <%= form_with model: [current_patient, @medication], local: true do |form| %>
        <div class="mb-3">
          <%= form.label :name, "名前", class: "form-label" %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="row mb-3">
          <div class="col-4">
            <%= form.label :dosage, "服用量", class: "form-label" %>
            <%= form.text_field :dosage, class: "form-control" %>
          </div>

          <div class="col-4">
            <%= form.label :start_date, "開始日", class: "form-label" %>
            <%= form.date_field :start_date, class: "form-control" %>
          </div>

          <div class="col-4">
            <%= form.label :end_date, "終了日", class: "form-label" %>
            <%= form.date_field :end_date, class: "form-control" %>
          </div>
        </div>


        <div class="row mb-3">
          <div class="col-4 time-input visible">
            <%= form.label :time1, "時間" %>
            <%= form.time_field :time1, class: "form-control time-field" %>
          </div>

          <div class="col-4 time-input label-placeholder <%= 'visible' if @medication.time1.present? %>" >
            <%= form.time_field :time2, class: "form-control time-field" %>
          </div>

          <div class="col-4 time-input label-placeholder <%= 'visible' if @medication.time2.present? %>">
            <%= form.time_field :time3, class: "form-control time-field" %>
          </div>
        </div>

        <div class="row">
          <div class="col-4 time-input <%= 'visible' if @medication.time3.present? %>" >
            <%= form.time_field :time4, class: "form-control time-field" %>
          </div>

          <div class="col-4 time-input <%= 'visible' if @medication.time4.present? %>" >
            <%= form.time_field :time5, class: "form-control time-field" %>
          </div>
        </div>

        <div class="mb-3 mt-3">
          <%= form.label :memo, "メモ", class: "form-label" %>
          <%= form.text_area :memo, class: "form-control large-text-area" %>
        </div>

        <div class="mb-2">
          <%= form.submit "更      新", class: "btn w-50 new-button" %>
        </div>

        <div class="mb-3">
          <%= link_to '削   除', patient_medication_path(@medication), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか' },class: "btn w-50 delete-button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

backend/app/views/medications/index.html.erb
<div class="container mt-5 mb-5">

  <%= link_to '＋ お薬を追加', new_patient_medication_path(current_patient), class: 'btn mb-0 add-medication' %>
  <hr>

  <% if @medications.present? %>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
      <% @medications.each do |medication| %>
        <div class="col">
          <div class="card h-100 medication-card">
            <div class="card-body">
              <div class="medication-card-title">
                <div class="medication-title"><%= medication.name %></div>
                <%= link_to image_tag("medication-edit.svg"), edit_patient_medication_path(current_patient, medication), class: 'edit-icon' %>
              </div>
              <div class="card-item">
                <span class="item-title">服用量 : </span>
                <span class="item-content"><%= medication.dosage %></span>
              </div>
              <div class="card-item">
                <span class="item-title">期 間 : </span>
                <span class="item-content"><%= medication.start_date.strftime("%-m月%-d日") %> 〜 <%= medication.end_date.strftime("%-m月%-d日") %></span>
              </div>
              <div class="card-item">
                <span class="item-title">時 間 : </span>
                <span class="item-content">
                  <% [medication.time1, medication.time2, medication.time3, medication.time4, medication.time5].compact.each do |time| %>
                    <span class="time-label"><%= time.strftime('%H:%M') %></span>
                  <% end %>
                </span>
              </div>

                <span class="item-title memo-toggle" style="cursor: pointer;">ロード中・・・</span>
                <div class="memo-content" style="display: none;">
                  <%= simple_format medication.memo %>
                </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="no-schedule">
      <%= image_tag "no-medication.svg", class: "no-schedule-img" %>
      <p>まだお薬が登録されていません</p>
    </div>
  <% end %>

</div>

backend/app/views/medications/new.html.erb
<div class="container mb-5">
  <%= link_to "戻る", patient_medications_path(current_patient), class: "btn back-button" %>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h3 class="text-center mb-3">お薬情報登録</h3>
      <hr>

      <%= render 'errors' %>
      <%= render 'form' %>
    </div>
  </div>
</div>