backend/config/routes.rb
Rails.application.routes.draw do

  resources :patients do
    resources :medications, except: [:show]
    resources :schedules, only: [:index] do
      post :update_confirmation, on: :collection
    end
  end
  # resources :medications, except: [:show]
  # resources :schedules, only: [:index]

  # post '/schedules/update_confirmation', to: 'schedules#update_confirmation'

  get 'rooms/show'

  root 'home#index'
  get 'home/index'
  get 'home/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # ログアウト時にエラーが出るので、以下を追加
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

backend/app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="flash flash-<%= key %>">
    <%= value %>
  </div>
<% end %>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeCareConnect | 在宅療養者の情報共有プラットフォーム</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="header">
      <% if user_signed_in? %> <!-- ログインしている場合 -->
        <div class="after-login">
          <%= link_to image_tag('hcc_logo.png', alt: 'HomeCareConnect', class: 'hcc-logo'), rooms_show_path %>

          <div class="user-menu">
            <%= image_tag "#{current_user.role}.png", class: "user-icon", id: "userIcon" %>
            <!-- <div class="user-icon" id="userIcon"></div> -->
            <div class="user-dropdown" id="userDropdown">
              <ul>
                <li class="user-name"><%= current_user.name %>（<%= role_in_japanese(current_user.role) %>）</li>
                <li><%= link_to raw('<i class="fa-solid fa-gear" style="color: #878787;"></i>  設定'), edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to raw('<i class="fa-regular fa-address-book" style="color: #787878;"></i> プロフィール・患者ID'), "#", id: "openModal"  %></li>
                <li class="divider"></li>
                <li class="logout-button"><%= link_to raw('<i class="fa-solid fa-right-to-bracket" style="color: #4d4d4d;"></i> ログアウト'), destroy_user_session_path, method: :delete %></li>
              </ul>
            </div>
          </div>

        </div>
      <% else %>  <!-- ログインしていない場合 -->
        <div class= "before-login" >
            <%= link_to image_tag('hcc_logo.png', alt: 'HomeCareConnect', class: "hcc-logo"), root_path %>
          <div class="login-assign">
              <a href="<%= new_user_session_path %>" class="btn login-button">ログイン</a>
              <a href="<%= new_user_registration_path %>" class="btn assign-button">無料で開始する</a>
          </div>
        </div>
      <% end %>
    </div>

    <!-- deviseのflashメッセージを表示する -->
    <div class="flash-container <%= user_signed_in? ? 'logged-in' : 'logged-out' %>">
      <%= render 'layouts/flash_messages' %>
    </div>

    <div class="container-fluid">
      <div class="row">
        <% if user_signed_in? %>  <!-- ログインしている場合 -->
        <!-- ここにサイドメニューを配置 -->
          <div class="side-menu">
            <div class="list-group">
              <a href="<%= rooms_show_path %>" class="list-side-menu <%= 'active' if current_page?(rooms_show_path) %>">
                <%= image_tag 'comment-dots-regular.svg', alt: 'チャット', class: 'icon-class' %>チャットルーム
              </a>
              <a href="<%= patient_schedules_path(current_patient) %>" class="list-side-menu <%= 'active' if current_page?(patient_schedules_path(current_patient)) %>">
                <%= image_tag 'clock-regular.svg', alt: 'スケジュール', class: 'icon-class' %>服用スケジュール
              </a>
              <a href="<%=  patient_medications_path(current_patient) %>" class="list-side-menu <%= 'active' if current_page?(patient_medications_path(current_patient)) %>">
                <%= image_tag 'rectangle-list-regular.svg', alt: 'お薬リスト', class: 'icon-class' %>お薬リスト
              </a>
            </div>
          </div>

          <! -- スマホ用にタブバーを設置 -->
          <div class="tab-bar">
            <a href="<%= rooms_show_path %>" class="tab-item <%= 'active' if current_page?(rooms_show_path) %>">
              <%= image_tag 'comment-dots-regular.svg', alt: 'チャット', class: 'tab-icon' %><span class="tab-name">チャット</span>
            </a>
            <a href="<%= patient_schedules_path(current_patient) %>" class="tab-item <%= 'active' if current_page?(patient_schedules_path(current_patient)) %>">
              <%= image_tag 'clock-regular.svg', alt: 'スケジュール', class: 'tab-icon' %><span class="tab-name">スケジュール</span>
            </a>
            <a href="<%=  patient_medications_path(current_patient) %>" class="tab-item <%= 'active' if current_page?(patient_medications_path(current_patient)) %>">
              <%= image_tag 'rectangle-list-regular.svg', alt: 'お薬リスト', class: 'tab-icon' %><span class="tab-name">リスト</span>
            </a>
          </div>

          <div class="content-area">
            <!-- ここに各ビューが表示される -->
            <%= yield %>

            <div id="userSettingsModal" class="modal">
              <div class="modal-content">
                <!-- ここまでモーダルウィンドウ、以下はモーダル内容 -->
                <div class="modal-header">
                  ユーザー情報
                  <span id="closeModal" >&times;</span>
                </div>

                <div class="container">
                  <div class="card-body">
                    <p><strong>ユーザーID:</strong> <%= current_user.login_id %></p>
                    <p><strong>ユーザー名:</strong> <%= current_user.name %></p>
                    <p><strong>メールアドレス:</strong> <%= current_user.email %></p>
                    <p><strong>ユーザータイプ:</strong> <%= role_in_japanese(current_user.role) %></p>
                    <p><strong>患者ID:</strong> <%= current_user.secret_patient_id %></p>
                    <p class="text-muted">パスワードはセキュリティ上表示されません。</p>
                  </div>
                </div>
              </div>
            </div>

          </div>
        <% else %>      <!-- ログイン前ー -->
          <div class="col-12">
            <!-- ここに各ビューが表示される -->
            <%= yield %>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>